version: '3'

services:
        db:
                image: postgres:latest
                volumes:
                        - ./data/postgres:/var/lib/postgresql/data
        web:
                build: .
                command: python /app/manage.py runserver 0.0.0.0:9996
                volumes:
                        - .:/app
                ports:
                        - '9996:9996'
                depends_on:
                        - db